version: '3.8'

services:
  converter:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./input:/app/input
      - ./output:/app/output
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1